@Echo Off 

Echo Initializing information......
Echo Preparing Updates......
Reg Add HKLM/SOFTWARE/Noam/WinLegacyUpdate /v UpdateEnabled /d 1 /t REG_DWORD
Echo Registering information.....
Echo Update Service Core - Loaded
Reg Add HKLM/SOFTWARE/Noam/WinLegacyUpdate /v StartUpdates /d 1 /t REG_DWORD
Mov %USERNAME%/Desktop/WinLegacyUpdate/LU.ps1 %USERNAME%/AppData/roaming/Microsoft/Windows/programs/startup
Echo Reading Configuration Files......
Echo Installing WinLegacyUpdate........
Echo Please Wait.....
color a
Restarting.......
Shutdown /r t 0
